config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  # splash page
  resources :statics, only:[:index]

  # admin
  resources :configs, only:[:index]

  # blogs / info
  resources :updates, only: [:index, :create]
  resources :rules, only: [:index]

  # organization stuff
  resources :tournaments, only: [:index, :show] do 
    resources :picks, only: [:index, :create]
  end
  resources :entries, only: [:create, :show]
  resources :picks, only: [:destroy]

  # game pieces
  resources :teams, only: [:index, :create]
  resources :games, only: [:index, :create]
  resources :results, only: [:create]

  root to: 'statics#index'
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
    before_action :redirect_unless_admin
    
    def index
        @picks = Pick.includes(:round, :team, :user).all.sort_by(&:entry)
    end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/configs/index.html.erb
<div class="container__col--single">
    <div>
        1. <%= link_to "Edit Games / Results", games_url, class: "link" %>
    </div>
    <div>
        2. <%= link_to "See All Users", users_url, class: "link" %>
    </div>
</div>
<br>
<br>
<br>
<h3 class="h3">All Picks</h3>
<table class="table">
    <tr class="table__row--title">
        <td class="table__title">User <span class="body body--italic"></span></td>
        <td class="table__item table__title">Round</td>
        <td class="table__item table__title">Team</td>
        <td class="table__item table__item--right table__title">Points</td>
        <td class="table__item table__item--right table__title">Multiplier</td>
    </tr>
    <% @picks.each_with_index do |pick| %> 
    <tr class="table__row">
        <td class="table__item">
            <span class="table__team-name">
                <%= pick.user.team_name %> 
            </span>
            <span class="table__user-name">
                <%= pick.user.name %> 
            </span>
        </td>
        <td class="table__item">
            <%= pick.round.name %>
        </td>
        <td class="table__item">
            <%= pick.team.name %>
        </td>
        <td class="table__item table__item--right">
            <%= pick.points %>
        </td>
        <td class="table__item table__item--right">
            <% if pick.multiplier == 2 %><span class="body body--bold">x2</span><% end %>
        </td>
    </tr>
    <% end %>
</table>