config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  # splash page
  resources :statics, only:[:index]

  # admin
  resources :configs, only:[:index]

  # blogs / info
  resources :updates, only: [:index, :create]
  resources :rules, only: [:index]

  # organization stuff
  resources :tournaments, only: [:index, :show] do 
    resources :picks, only: [:index, :create]
  end
  resources :entries, only: [:create, :show]
  resources :picks, only: [:destroy]

  # game pieces
  resources :teams, only: [:index, :create]
  resources :games, only: [:index, :create]
  resources :results, only: [:create]

  root to: 'statics#index'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    has_many :entries
    has_many :rounds
    has_many :games
    has_many :results, through: :games

    has_many :users, through: :entries
    has_many :picks, through: :entries

    def picks_open?
        if rounds.empty?
            return false
        end

        now = DateTime.now
        rounds
            .select {|round| round.picks_open? }
            .any?
    end

    def scoring_rounds
        closed_rounds = rounds.select { |round| round.picks_close < DateTime.now }
        return [] if closed_rounds.length < 2
        return closed_rounds.last(2)
    end

    def self.score(tournament)
        # set scores = tournament.allowance if we don't have two rounds yet
        scoring_rounds = tournament.scoring_rounds
        scoring_games = tournament.games.select { |game| scoring_rounds.map(&:id).include?(game.round_id)  }
        if scoring_rounds.empty?
            return tournament.entries.reduce(Hash.new) do |memo, entry|
                memo[entry.user] = tournament.allowance
                memo
            end
        end

        # otherwise, do the super reduce
        team_cache = Team.all
        Tournament
            .includes(:entries, :picks, :games, :rounds, :results, :users)
            .find(tournament.id)
            .entries
            .reduce(Hash.new) do |memo, entry| 
                # filter all picks to eliminate those not from the scoring rounds
                scoring_picks = entry
                    .picks
                    .select { |pick| scoring_rounds.map(&:id).include?(pick.round_id) }
                    .select{ |pick| !scoring_games.find { |game| game.matches_pick(pick) }.nil? }

                # make a hash of usernames & picks with game:result
                memo[entry.user] = scoring_picks.select { |pick| !pick.game.results.empty? }
                memo
            end
            .reduce(Hash.new) do |memo, (entry, picks)|
                memo[entry] = picks.map do |pick|
                    pick_team = team_cache.find { |team| team.id == pick.team_id}
                    {
                        points: pick.points,
                        seed: pick_team.seed == 1 ? 1.5 : pick_team.seed,
                        multiplier: pick.multiplier,
                        result: tournament.games.select { |game| game.round_id == pick.round_id }.flat_map(&:results).find { |result| result.team_id == pick.team_id }
                    }
                end
                memo
            end
            .reduce(Hash.new) do |memo, (entry, pick_outcomes)|
                pick_payouts_arr = pick_outcomes.map do |pick_outcome|
                    pick_outcome[:result].loss? ? 0 : pick_outcome[:points] * pick_outcome[:multiplier] * pick_outcome[:seed]
                end
                memo[entry] = pick_payouts_arr.sum
                memo
            end
    end

    def self.score_and_cache(tournament) 
        score_hash = Tournament.score(tournament)
        score_hash.each do |(user, points)|
            entry = Entry.find_by(user_id: user.id, tournament_id: tournament.id)
            entry.points = points
            entry.save
        end
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
    before_action :redirect_if_logged_out

    def index
        @tournaments = Tournament.all
    end

    def show
        @tournament = Tournament.find(params[:id])
        @current_user_has_entered = current_user.tournaments.include?(@tournament)

        @entries = @tournament
                        .entries
                        .includes(:user)
                        .reject { |entry| entry.user.nil? }
                        .sort_by { |entry| -entry[:points] }

        @users = @tournament.users
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/index.html.erb
<div class="container__col--single">
    <table class="table">
        <tr class="table__row--title">
            <td class="table__title">Current Tournaments</td>
            <td></td>
        </tr>
        <% @tournaments.each do |tournament| %> 
        <tr class="table__row">
            <td class="table__item">
            <%= tournament.name %>  
            </td>
            <td class="table__item table__item--right">
                <% if current_user.registered?(tournament) %>
                    <%= link_to "Standings", tournament_url(tournament), class: "link" %>
                <% else %>
                    <%= link_to "Enter", tournament_url(tournament), class: "link" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/tournaments/show.html.erb
<h2 class="h3 h3--uppercase">
    <%= @tournament.name %>
</h2>

<% if !@current_user_has_entered %>
<div class="alert alert--danger">
    <span class="body body--bold">Entries are closed.</span> But there's always next year.
</div>
<% end %>

<% if @current_user_has_entered %>
    <% if @tournament.picks_open? %>
    <div class="alert alert--success">
        <span class="body body--bold">Picks are open!</span> <%= link_to "Make (or edit) your picks here", tournament_picks_url(@tournament), class: "link link--white" %>.
    </div>
    <% else %>
    <div class="alert alert--danger">
        <span class="body body--bold">Games in progress.</span> <%= link_to "Read updates here.", updates_url %>
    </div>
    <% end %>
<% end %>

<table class="table">
    <tr class="table__row--title">
        <td class="table__title">Teams <span class="body body--italic">(<%= @entries.count %> entered)</span></td>
        <td class="table__item table__item--right table__title">Score</td>
    </tr>
    <% @entries.each_with_index do |entry, idx| %> 
    <tr class="table__row">
        <td class="table__item">
            <% user = @users.find { |user| entry.user_id == user.id } %>
            <span><%= idx + 1 %>. </span>
            <span class="table__team-name">
                <%= link_to user.team_name, entry_url(entry), class: "link" %>
            </span>
            <span class="table__user-name">
                <%= user.name %> 
            </span>
            <span class="table__city">
                <%= user.city %>  
            </span>
        </td>
        <td class="table__item table__item--right">
            <%= entry.points %>
        </td>
    </tr>
    <% end %>
</table>