config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  # splash page
  resources :statics, only:[:index]

  # admin
  resources :configs, only:[:index]

  # blogs / info
  resources :updates, only: [:index, :create]
  resources :rules, only: [:index]

  # organization stuff
  resources :tournaments, only: [:index, :show] do 
    resources :picks, only: [:index, :create]
  end
  resources :entries, only: [:create, :show]
  resources :picks, only: [:destroy]

  # game pieces
  resources :teams, only: [:index, :create]
  resources :games, only: [:index, :create]
  resources :results, only: [:create]

  root to: 'statics#index'
end

app/views/shared/_nav.html.erb
<div class="nav nav--title">
  <%= link_to ENV["app_name"], root_url, class: "nav__link nav__link--title" %>
</div>
<div class="nav">
  <% if !current_user.nil? && admin? %>
    <%= link_to "Config", configs_url, class: "nav__link" %>
  <% end %>
    <%= link_to "Rules", rules_url, class: "nav__link" %>
  <% if logged_in? %>
    <%= link_to "Standings", tournament_url(1), class: "nav__link" %>
    <%= link_to "Your Picks", tournament_picks_url(1), class: "nav__link" %>
    <%= link_to "Blog", updates_url, class: "nav__link" %>
    <%= link_to "Log Out", session_url, method: :delete, class: "nav__link" %>
  <% else %>
    <%= link_to "Log In", new_session_url, class: "nav__link" %>
    <%= link_to "Sign Up", new_user_url, class: "nav__link" %>
  <% end %>
</div>