config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index] do
    collection do
      get 'scoreboard'
    end
  end

  resource :session, only: [:new, :create, :destroy]

  # splash page
  resources :statics, only:[:index]

  # admin
  resources :configs, only:[:index]

  # blogs / info
  resources :updates, only: [:index, :create]
  resources :rules, only: [:index]

  # organization stuff
  resources :tournaments, only: [:index, :show] do 
    resources :picks, only: [:index, :create]
  end
  resources :entries, only: [:create, :show]
  resources :picks, only: [:destroy]

  # game pieces
  resources :teams, only: [:index, :create]
  resources :games, only: [:index, :create]
  resources :results, only: [:create]

  root to: 'statics#index'
end

app/models/game.rb
class Game < ApplicationRecord
    validate :one_game_per_team_per_round, :team_cannot_play_itself
    
    belongs_to :home_team, class_name: "Team", foreign_key: "home_team_id"
    belongs_to :away_team, class_name: "Team", foreign_key: "away_team_id"
    belongs_to :round
    belongs_to :tournament
    has_many :results

    def winner
        winner = results.find { |res| res.win == true }

        return winner.nil? ? nil : winner.team
    end

    def <=>(game)
        if self.round_id != game.round_id
            return self.round_id <=> game.round_id
        elsif self.winner == nil
            return -1
        else
            return 1
        end
    end

    def matches_pick(pick)
        round_id == pick.round_id && 
            (home_team_id == pick.team_id || away_team_id == pick.team_id)
    end

    private
    def one_game_per_team_per_round
        if (Game.where(tournament_id: self.tournament_id, home_team_id: self.home_team_id, round_id: self.round_id).any? || 
            Game.where(tournament_id: self.tournament_id, away_team_id: self.away_team_id, round_id: self.round_id).any?)
            errors[:pick] << ": Only one game per team per round!"
        end
    end

    def team_cannot_play_itself
        if (self.home_team_id == self.away_team_id)
            errors[:pick] << ": Team cannot play itself!"
        end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :redirect_unless_admin

    def index 
        @games = Game
            .includes(:results, :home_team, :away_team)
            .all
            .sort_by { |game| -game.round_id }


        losses_team_ids = Result.all.select { |result| result.loss? }.map(&:team_id)
        @teams = Team.all
            .select { |team| !losses_team_ids.include?(team.id) }
            .sort_by { |team| team.seed }
        @rounds = Round.last(2)
        @tournaments = Tournament.all
    end

    def create
        @game = Game.new(game_params)
        @game.tournament_id = Tournament.first.id

        if @game.save
            redirect_to games_url
        else
            flash[:errors] = @game.errors.full_messages
            redirect_to games_url
        end
    end

    private
    def game_params
        params.require(:game).permit(:home_team_id, :away_team_id, :round_id, :tournament_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h3 class="h3">New Game</h3>
<% if flash[:errors] %>
    <% flash[:errors].each do |error|%>
        <div class="alert alert--danger">
            <%= error %>
        </div>
    <% end %>
<% end %>
<form action="<%= games_url %>" method="POST" class="form">
    <%= auth_token %>
    <div class="form__row">
        <p class="body body--bold">Home Team</p>
        <select name="game[home_team_id]">
            <% @teams.each do |team| %>
            <option value="<%= team.id %>">(<%= team.seed %>) <%= team.name %></option>
            <% end %>
        </select>
    </div>
    <div class="form__row">
        <p class="body body--bold">Away Team</p>
        <select name="game[away_team_id]">
            <% @teams.each do |team| %>
            <option value="<%= team.id %>">(<%= team.seed %>) <%= team.name %></option>
            <% end %>
        </select>
    </div>
    <div class="form__row">
        <p class="body body--bold">Round</p>
        <select name="game[round_id]">
            <% @rounds.each do |round| %>
            <option value="<%= round.id %>"><%= round.name %></option>
            <% end %>
        </select>
    </div>
    <div class="form__row">
        <input type="submit" class="button" value="Create Game">
    </div>
</form>
<table class="table">
    <tr class="table__row--title">
        <td class="table__title">Round</td>
        <td class="table__item">Home Team</td>
        <td class="table__item">Away Team</td>
        <td class="table__item">Winner</td>
        <td class="table__item">Region(s)</td>
    </tr>
    <% @games.each do |game| %> 
    <tr class="table__row">
        <td class="table__item">
            <%= game.round.name %> 
        </td>
        <td class="table__item">
            (<%= game.home_team.seed %>)
            <%= game.home_team.name %>
            <% if game.winner.nil? %>
            <form action="<%= results_url %>" method="POST">
                <%= auth_token %>
                <button>(Mark Winner)</button>
                <input type="hidden" name="result[team_id]" value="<%= game.home_team_id %>">
                <input type="hidden" name="result[game_id]" value="<%= game.id %>">
                <input type="hidden" name="result[win]" value="true">
            </form>
            <% end %>
        </td>
        <td class="table__item">
            (<%= game.away_team.seed %>) <%= game.away_team.name %> 
            <% if game.winner.nil? %>
            <form action="<%= results_url %>" method="POST">
                <%= auth_token %>
                <button>(Mark Winner)</button>
                <input type="hidden" name="result[team_id]" value="<%= game.away_team_id %>">
                <input type="hidden" name="result[game_id]" value="<%= game.id %>">
                <input type="hidden" name="result[win]" value="true">
            </form>
            <% end %>
        </td>
        <td class="table__item">
            <% if game.results.length == 0 %>
            <span class="body body--italic">none yet</span>
            <% else %>
            <span class="body body--bold"><%= game.winner.name %></span>
            <% end %>
        </td>
        <td class="table__item">
            <%= game.home_team.region %> / <%= game.away_team.region %> 
        </td>
    </tr>
    <% end %>
</table>